config/routes.rb
Rails.application.routes.draw do
  get 'devices/require'

  get 'devices/apply'

  get 'devices/contact'

  resources :devices

end

app/models/device.rb
class Device < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_action :set_device, only: [:show, :edit, :update, :destroy]

  # GET /devices
  # GET /devices.json
  def index
    @devices = Device.where(status: 1).paginate page: params[:page], per_page: 20
  end

  # GET /devices/1
  # GET /devices/1.json
  def show
  end

  # GET /devices/new
  def new
    @device = Device.new
  end

  # GET /devices/1/edit
  def edit
  end

  # GET /devices/require
  def require
    @device = Device.new
  end

  # GET /devices/apply
  def apply
    @devices = Device.where(status: 0)
  end

  # POST /devices
  # POST /devices.json
  def create
    @device = Device.new(device_params)

    respond_to do |format|
      if @device.save
        format.html { redirect_to @device, notice: 'Device was successfully created.' }
        format.json { render :show, status: :created, location: @device }
      else
        format.html { render :new }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /devices/1
  # PATCH/PUT /devices/1.json
  def update
    respond_to do |format|
      if @device.update(device_params)
        format.html { redirect_to @device, notice: 'Device was successfully updated.' }
        format.json { render :show, status: :ok, location: @device }
      else
        format.html { render :edit }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /devices/1
  # DELETE /devices/1.json
  def destroy
    @device.destroy
    respond_to do |format|
      format.html { redirect_to devices_url, notice: 'Device was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_device
      @device = Device.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def device_params
     params.require(:device).permit(:ip, :os_type, :os_name, :os_bit, :browser_version, :browser_bit, :owner, :description, :remark, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/views/devices/_form.html.erb
<%= form_for(@device, html: {class: 'form-horizontal'}) do |f| %>
  <% if @device.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@device.errors.count, "error") %> prohibited this device from being saved:</h2>

      <ul>
      <% @device.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
    <div class="control-group">
      <!-- Text input-->
      <label class="control-label">IP地址:</label>
      <div class="controls">
        <%= f.text_field :ip %>           
      </div>
    </div>
    <div class="control-group">
      <!-- Text input-->
      <label class="control-label">系统类型:</label>
      <div class="controls">
        <%= f.text_field :os_type %>           
      </div>
    </div>
    <div class="control-group">
      <!-- Text input-->
      <label class="control-label">系统名称:</label>
      <div class="controls">
        <%= f.text_field :os_name %>           
      </div>
    </div>
    <div class="control-group">
      <!-- Text input-->
      <label class="control-label">系统位数:</label>
      <div class="controls">
        <%= f.text_field :os_bit %>           
      </div>
    </div>
    <div class="control-group">
      <!-- Text input-->
      <label class="control-label">浏览器版本:</label>
      <div class="controls">
        <%= f.text_field :browser_version %>           
      </div>
    </div>
    <div class="control-group">
      <!-- Text input-->
      <label class="control-label">浏览器位数:</label>
      <div class="controls">
        <%= f.text_field :browser_bit %>           
      </div>
    </div>
    <div class="control-group">
      <!-- Text input-->
      <label class="control-label">负责人:</label>
      <div class="controls">
        <%= f.text_field :owner %>           
      </div>
    </div>
    <div class="control-group">
      <!-- Text input-->
      <label class="control-label">用途描述:</label>
      <div class="controls">
        <%= f.text_field :description %>           
      </div>
    </div>
    <div class="control-group">
      <!-- Text input-->
      <label class="control-label">备注信息:</label>
      <div class="controls">
        <%= f.text_area :remark %>           
      </div>
    </div>
    <%= f.hidden_field :status, {value: 1} %>
    <div class="control-group">
      <label></label>
      <!-- Button -->
      <div class="controls">
        <%= f.submit "保存", {class: 'btn btn-success'}%>
        <%= link_to "返回", devices_path, {class: 'btn'} %>
      </div>
    </div>
  </fieldset>
<% end %>

app/views/devices/apply.html.erb
<h3>待审批设备列表</h3>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>申请人</th>
      <th>系统类型</th>
      <th>系统名称</th>
      <th>系统位数</th>
      <th>浏览器版本</th>
      <th>浏览器位数</th>      
      <th>用途描述</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @devices.each do |device| %>
      <tr class="<%= cycle('info', '') %>">
        <td><%= device.owner %></td>
        <td><%= device.os_type %></td>
        <td><%= device.os_name %></td>
        <td><%= device.os_bit %></td>
        <td><%= device.browser_version %></td>
        <td><%= device.browser_bit %></td>        
        <td><%= device.description %></td>
        <td><%= link_to '通过', edit_device_path(device), class: 'btn btn-success' %></td>
        <td><%= link_to '删除', device, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/devices/contact.html.erb
<form class="form-horizontal">
  <fieldset>
    <div id="legend" class="">
      <legend class="">联系方式</legend>
    </div>
    <div class="control-group">
      <!-- Text input-->
      <label class="control-label">负责人</label>
      <div class="controls">
        <input type="text" class="input-xlarge" value="赵元凯" disabled="true">            
      </div>
    </div>
    <div class="control-group">
      <!-- Text input-->
      <label class="control-label">电话</label>
      <div class="controls">
        <input type="text" class="input-xlarge" value="58118551" disabled="true">            
      </div>
    </div>    
    <div class="control-group">
      <!-- Text input-->
      <label class="control-label"></label>
      <div class="controls">
        <%= link_to '管理员添加设备入口', new_device_path, {class: 'btn btn-large btn-info'} %>
      </div>
    </div>   
  </fieldset>
</form>
<p></p>

app/views/devices/edit.html.erb
<h3>编辑设备信息</h3>

<%= render 'form' %>

app/views/devices/index.html.erb
<h3>在用设备列表</h3>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>IP</th>
      <!--
      <th>Os type</th>
      -->
      <th>系统名称</th>
      <th>系统位数</th>
      <th>浏览器</th>
      <th>浏览器位数</th>
      <th>负责人</th>
      <th>用途描述</th>
      <!--
      <th>Remark</th>
      -->
      <th colspan="3">管理</th>
    </tr>
  </thead>

  <tbody>
    <% @devices.each do |device| %>
      <tr class="<%= cycle('info', '') %>">
        <td><%= device.ip %></td>
        <!--
        <td><%= device.os_type %></td>
        -->
        <td><%= device.os_name %></td>
        <td><%= device.os_bit %></td>
        <td><%= device.browser_version %></td>
        <td><%= device.browser_bit %></td>
        <td><%= device.owner %></td>
        <td><%= device.description %></td>
        <!--
        <td><%= device.remark %></td>
        -->
        <td><%= link_to '查看详细', device %></td>
        <td><%= link_to '编辑', edit_device_path(device) %></td>
        <td><%= link_to '删除', device, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<p><%= will_paginate @devices %></p>
<br>


<%= link_to '设备申请', devices_require_path, {class: 'btn btn-primary'} %>

app/views/devices/new.html.erb
<h3>新增设备信息</h3>

<%= render 'form' %>

app/views/devices/require.html.erb
<%= form_for(@device, html: {class: 'form-horizontal'}) do |f| %>
  <% if @device.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@device.errors.count, "error") %> prohibited this device from being saved:</h2>

      <ul>
      <% @device.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>  

  <fieldset>
    <div id="legend" class="">
      <legend class="">申请设备</legend>
    </div>
    <div class="control-group">
      <!-- Text input-->
      <label class="control-label">申请人:</label>
      <div class="controls">
        <%= f.text_field :owner %>           
      </div>
    </div>
    <div class="control-group">
      <!-- Text input-->
      <label class="control-label">系统类别:</label>
      <div class="controls">
        <%= f.text_field :os_type %>  
      </div>
    </div>
    <div class="control-group">
      <!-- Text input-->
      <label class="control-label">系统名称:</label>
      <div class="controls">
        <%= f.text_field :os_name %>  
      </div>
    </div>
    <div class="control-group">
      <!-- Text input-->
      <label class="control-label">系统位数:</label>
      <div class="controls">
        <%= f.text_field :os_bit %>  
      </div>
    </div>
    <div class="control-group">
      <!-- Text input-->
      <label class="control-label">浏览器版本:</label>
      <div class="controls">
        <%= f.text_field :browser_version %>  
      </div>
    </div>
    <div class="control-group">
      <!-- Text input-->
      <label class="control-label">浏览器位数:</label>
      <div class="controls">
        <%= f.text_field :browser_bit %>  
      </div>
    </div>
    <div class="control-group">
      <!-- Text input-->
      <label class="control-label">用途描述:</label>
      <div class="controls">
        <%= f.text_field :description %>  
      </div>
    </div>
    <%= f.hidden_field :status, {value: 0}  %>    
    <div class="control-group">
      <label></label>
      <!-- Button -->
      <div class="controls">
        <%= f.submit "提交申请", {class: 'btn btn-success'}%>
        <%= link_to "返回", devices_path, {class: 'btn'} %>
      </div>
    </div>
  </fieldset>
<% end %>

app/views/devices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>IP地址:</strong>
  <%= @device.ip %>
</p>

<p>
  <strong>系统类型:</strong>
  <%= @device.os_type %>
</p>

<p>
  <strong>系统名称:</strong>
  <%= @device.os_name %>
</p>

<p>
  <strong>系统位数:</strong>
  <%= @device.os_bit %>
</p>

<p>
  <strong>浏览器版本:</strong>
  <%= @device.browser_version %>
</p>

<p>
  <strong>浏览器位数:</strong>
  <%= @device.browser_bit %>
</p>

<p>
  <strong>负责人:</strong>
  <%= @device.owner %>
</p>

<p>
  <strong>用途描述:</strong>
  <%= @device.description %>
</p>

<p>
  <strong>备注:</strong>
  <%= @device.remark %>
</p>

<%= link_to 'Back', devices_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Devices</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>     
          <%= link_to '在用设备列表', devices_path, {class: 'brand'} %></a>
          <div class="nav-collapse collapse">
            <ul class="nav">              
              <li><%= link_to '申请设备', devices_require_path %></li>
              <li><%= link_to '待审批设备', devices_apply_path %></li>
              <li><%= link_to '联系我们', devices_contact_path %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <%= yield %>
    </div> <!-- /container -->
</body>
</html>